/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DeFund {
  export type CampaignStruct = {
    creator: AddressLike;
    title: string;
    description: string;
    fundingGoal: BigNumberish;
    raisedAmount: BigNumberish;
    releasedAmount: BigNumberish;
    state: BigNumberish;
    milestoneCount: BigNumberish;
    currentMilestone: BigNumberish;
    createdAt: BigNumberish;
  };

  export type CampaignStructOutput = [
    creator: string,
    title: string,
    description: string,
    fundingGoal: bigint,
    raisedAmount: bigint,
    releasedAmount: bigint,
    state: bigint,
    milestoneCount: bigint,
    currentMilestone: bigint,
    createdAt: bigint
  ] & {
    creator: string;
    title: string;
    description: string;
    fundingGoal: bigint;
    raisedAmount: bigint;
    releasedAmount: bigint;
    state: bigint;
    milestoneCount: bigint;
    currentMilestone: bigint;
    createdAt: bigint;
  };

  export type MilestoneStruct = {
    description: string;
    fundsAllocated: BigNumberish;
    proofUrl: string;
    state: BigNumberish;
    confidence: BigNumberish;
  };

  export type MilestoneStructOutput = [
    description: string,
    fundsAllocated: bigint,
    proofUrl: string,
    state: bigint,
    confidence: bigint
  ] & {
    description: string;
    fundsAllocated: bigint;
    proofUrl: string;
    state: bigint;
    confidence: bigint;
  };
}

export interface DeFundInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "backers"
      | "campaignCounter"
      | "campaigns"
      | "claimRefund"
      | "contribute"
      | "contributions"
      | "createCampaign"
      | "getBackerCount"
      | "getCampaign"
      | "getContractBalance"
      | "getContribution"
      | "getMilestone"
      | "milestones"
      | "setVerifier"
      | "submitMilestone"
      | "verifier"
      | "verifyMilestone"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCompleted"
      | "CampaignCreated"
      | "CampaignFailed"
      | "ContributionReceived"
      | "FundsReleased"
      | "MilestoneSubmitted"
      | "MilestoneVerified"
      | "RefundClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "backers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, BigNumberish, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getBackerCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContribution",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMilestone",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyMilestone",
    values: [BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "backers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "campaignCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBackerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyMilestone",
    data: BytesLike
  ): Result;
}

export namespace CampaignCompletedEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    title: string,
    fundingGoal: BigNumberish,
    milestoneCount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    title: string,
    fundingGoal: bigint,
    milestoneCount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    title: string;
    fundingGoal: bigint;
    milestoneCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFailedEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    backer: AddressLike,
    amount: BigNumberish,
    totalRaised: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    backer: string,
    amount: bigint,
    totalRaised: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    backer: string;
    amount: bigint;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    milestoneIndex: bigint,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneSubmittedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    proofUrl: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    milestoneIndex: bigint,
    proofUrl: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
    proofUrl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneVerifiedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    passed: boolean,
    confidence: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    milestoneIndex: bigint,
    passed: boolean,
    confidence: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    milestoneIndex: bigint;
    passed: boolean;
    confidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    backer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    backer: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    backer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeFund extends BaseContract {
  connect(runner?: ContractRunner | null): DeFund;
  waitForDeployment(): Promise<this>;

  interface: DeFundInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  backers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  campaignCounter: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        fundingGoal: bigint;
        raisedAmount: bigint;
        releasedAmount: bigint;
        state: bigint;
        milestoneCount: bigint;
        currentMilestone: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  claimRefund: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  contribute: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "payable"
  >;

  contributions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _fundingGoal: BigNumberish,
      _milestoneDescriptions: string[],
      _milestoneAllocations: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;

  getBackerCount: TypedContractMethod<
    [_campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  getCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [DeFund.CampaignStructOutput],
    "view"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getContribution: TypedContractMethod<
    [_campaignId: BigNumberish, _backer: AddressLike],
    [bigint],
    "view"
  >;

  getMilestone: TypedContractMethod<
    [_campaignId: BigNumberish, _milestoneIndex: BigNumberish],
    [DeFund.MilestoneStructOutput],
    "view"
  >;

  milestones: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, bigint] & {
        description: string;
        fundsAllocated: bigint;
        proofUrl: string;
        state: bigint;
        confidence: bigint;
      }
    ],
    "view"
  >;

  setVerifier: TypedContractMethod<
    [_newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  submitMilestone: TypedContractMethod<
    [_campaignId: BigNumberish, _proofUrl: string],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  verifyMilestone: TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _passed: boolean,
      _confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "backers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaignCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        fundingGoal: bigint;
        raisedAmount: bigint;
        releasedAmount: bigint;
        state: bigint;
        milestoneCount: bigint;
        currentMilestone: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _fundingGoal: BigNumberish,
      _milestoneDescriptions: string[],
      _milestoneAllocations: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBackerCount"
  ): TypedContractMethod<[_campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish],
    [DeFund.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContribution"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _backer: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _milestoneIndex: BigNumberish],
    [DeFund.MilestoneStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, bigint] & {
        description: string;
        fundsAllocated: bigint;
        proofUrl: string;
        state: bigint;
        confidence: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<[_newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMilestone"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _proofUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyMilestone"
  ): TypedContractMethod<
    [
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _passed: boolean,
      _confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CampaignCompleted"
  ): TypedContractEvent<
    CampaignCompletedEvent.InputTuple,
    CampaignCompletedEvent.OutputTuple,
    CampaignCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFailed"
  ): TypedContractEvent<
    CampaignFailedEvent.InputTuple,
    CampaignFailedEvent.OutputTuple,
    CampaignFailedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionReceived"
  ): TypedContractEvent<
    ContributionReceivedEvent.InputTuple,
    ContributionReceivedEvent.OutputTuple,
    ContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneSubmitted"
  ): TypedContractEvent<
    MilestoneSubmittedEvent.InputTuple,
    MilestoneSubmittedEvent.OutputTuple,
    MilestoneSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneVerified"
  ): TypedContractEvent<
    MilestoneVerifiedEvent.InputTuple,
    MilestoneVerifiedEvent.OutputTuple,
    MilestoneVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;

  filters: {
    "CampaignCompleted(uint256)": TypedContractEvent<
      CampaignCompletedEvent.InputTuple,
      CampaignCompletedEvent.OutputTuple,
      CampaignCompletedEvent.OutputObject
    >;
    CampaignCompleted: TypedContractEvent<
      CampaignCompletedEvent.InputTuple,
      CampaignCompletedEvent.OutputTuple,
      CampaignCompletedEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignFailed(uint256)": TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;
    CampaignFailed: TypedContractEvent<
      CampaignFailedEvent.InputTuple,
      CampaignFailedEvent.OutputTuple,
      CampaignFailedEvent.OutputObject
    >;

    "ContributionReceived(uint256,address,uint256,uint256)": TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;
    ContributionReceived: TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;

    "FundsReleased(uint256,uint256,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "MilestoneSubmitted(uint256,uint256,string)": TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;
    MilestoneSubmitted: TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;

    "MilestoneVerified(uint256,uint256,bool,uint8)": TypedContractEvent<
      MilestoneVerifiedEvent.InputTuple,
      MilestoneVerifiedEvent.OutputTuple,
      MilestoneVerifiedEvent.OutputObject
    >;
    MilestoneVerified: TypedContractEvent<
      MilestoneVerifiedEvent.InputTuple,
      MilestoneVerifiedEvent.OutputTuple,
      MilestoneVerifiedEvent.OutputObject
    >;

    "RefundClaimed(uint256,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
  };
}
